### ISSUE TITLE
代理对象生成逻辑问题

### ISSUE THREAD

**Issue by susanbushisan** [DerekYRC/mini-spring#19]
分支：main/populate-proxy-bean-with-property-values
具体描述：在org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory#resolveBeforeInstantiation的方法中理论上是提前返回代理对象，会使用applyBeanPostProcessorsBeforeInstantiation方法，结果实现类中返回null从而走applyBeanPostProcessorsAfterInitialization方法，这完全没有必要只会增加代码的理解难度。建议将逻辑优化一下。

**Comment by DerekYRC** [comment]
> 提前返回代理对象，会使用applyBeanPostProcessorsBeforeInstantiation方

不是很明白你的意思，这个逻辑跟spring保持一致的

**Comment by susanbushisan** [comment]
我的意思是目前这个方法applyBeanPostProcessorsBeforeInstantiation，永远返回null，即使和spring结构一致也是不应该的
