### ISSUE TITLE
项目时长

### ISSUE THREAD

**Issue by songchuanl** [DerekYRC/mini-spring#45]
想问一下作者这个项目大概需要多长时间才能跟着做完呢？

**Comment by DerekYRC** [comment]
@songchuanl 有小伙伴反馈学完本项目耗时1-2个月。有问题随时沟通哈

**Comment by songchuanl** [comment]
谢谢作者

**Comment by rookiiiie** [comment]
> 

大佬，这个很有必要从0开始自己敲一遍吗? 我感觉就看看代码实现的思想就差不多了。。这个应该没必要记忆太多细节吧？。。

**Comment by DerekYRC** [comment]
@rookiiiie 个人感觉看懂源码和手敲出来差别还是很大的，自己手敲能极大加深印象。spring是一个很优秀的框架，熟悉spring源码之后再阅读其他框架源码会非常轻松，所以如果spring是你阅读源码的第一个框架的话，非常值得下功夫去学习spring源码
