### ISSUE TITLE
resolveBeforeInstantiation()方法返回的代理对象放入singletonObjects里面吗？

### ISSUE THREAD

**Issue by ccl125** [DerekYRC/mini-spring#50]
看到[动态代理融入bean生命周期](https://github.com/DerekYRC/mini-spring/blob/main/changelog.md#%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E8%9E%8D%E5%85%A5bean%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)这节，有些疑问：
1、 这节resolveBeforeInstantiation()方法生成的代理对象没有放在单例池里面，导致refresh()方法默认提前实例化单例bean的时候会执行一遍创建对象的过程，接着测试方法里面再去调用getBean()方法又会重写再执行一遍创建对象的过程，这里我认为代理对象默认也是单例的，好像应该在创建完成之后放在singletonObjects里面更合适一点。然后我看到下面的[bug fix：没有为代理bean设置属性（discovered and fixed by @kerwin89）](https://github.com/DerekYRC/mini-spring/blob/main/changelog.md#bug-fix%E6%B2%A1%E6%9C%89%E4%B8%BA%E4%BB%A3%E7%90%86bean%E8%AE%BE%E7%BD%AE%E5%B1%9E%E6%80%A7discovered-and-fixed-by-kerwin89)这节的内容，修复了[动态代理融入bean生命周期](https://github.com/DerekYRC/mini-spring/blob/main/changelog.md#%E5%8A%A8%E6%80%81%E4%BB%A3%E7%90%86%E8%9E%8D%E5%85%A5bean%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)这节中没有为代理对象设置属性的bug，通过这节中的方式修饰后，生成的代理对象就会走正常的创建完默认单例的对象存入singletonObjects中的流程，也就是在测试的时候，加载完xml文件，调用getBean()方法的时候就直接从singletonObjects中取出来，而不需要重新再执行一遍创建对象的过程了。疑问的点在于我又去重新看了下spring的源码，发现spring中通过resolveBeforeInstantiation(beanName, mbdToUse)方法返回代理对象后就直接返回了，spring中也没有把这个代理对象存储。那这个生成的代理对象到底应该存储起来吗？这里可能会涉及到后面循环依赖的内容，不知道是不是我看到那里就不会纠结这里的内容了
2、[bug fix：没有为代理bean设置属性（discovered and fixed by @kerwin89）](https://github.com/DerekYRC/mini-spring/blob/main/changelog.md#bug-fix%E6%B2%A1%E6%9C%89%E4%B8%BA%E4%BB%A3%E7%90%86bean%E8%AE%BE%E7%BD%AE%E5%B1%9E%E6%80%A7discovered-and-fixed-by-kerwin89)这节内容修改后，生成代理对象的地方应该就是我下图中划的地方吧。
![Snipaste_2023-04-03_23-55-25](https://user-images.githubusercontent.com/62643433/229563804-b4a17e5d-710e-4d22-8c4a-37618e441952.png)

**Comment by DerekYRC** [comment]
@ccl125 

1、我也很疑惑resolveBeforeInstantiation方法的作用，在spring中没有具体的应用。看spring源码的对于该方法的注释，这个方法是在bean实例化前提供一个短路的机会，当返回bean不为null时，不继续走spring的bean实例化流程。

![image](https://user-images.githubusercontent.com/44155264/229680291-52d361b4-858c-4b53-952c-ea327653512a.png)

2、对的。有空我更新下流程图。

谢谢你的支持！

**Comment by ccl125** [comment]
谢谢作者大大的解答。
网上搜了下资料，这个resolveBeforeInstantiation()方法相当于spring留下的一个扩展接口，可以通过继承子类的方式，返回bean，而不走spring正常createBean的方式。
https://juejin.cn/post/7068511224471748645
