### ISSUE TITLE
关于ValueAnnotationTest

### ISSUE THREAD

**Issue by quincysky** [DerekYRC/mini-spring#52]
在对应的**value-annotation.xml**文件中是不是没有注册对应的**AutowiredAnnotationBeanProcessor**

**Comment by DerekYRC** [comment]
@quincysky ClassPathBeanDefinitionScanner#doScan方法中注册AutowiredAnnotationBeanProcessor
![image](https://user-images.githubusercontent.com/44155264/233249719-4a531df1-0de5-4a29-beb9-71591aa239d2.png)

**Comment by quincysky** [comment]
感谢感谢
