### ISSUE TITLE
尊敬的大佬, 在value-annotation 分支中, 测试用例跑不通

### ISSUE THREAD

**Issue by CarsonLuo** [DerekYRC/mini-spring#57]
需要在该分支的测试包下的 value-annotation.xml 添加
\<bean class="org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor"/\>

**Comment by CarsonLuo** [comment]
" <bean class="org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor"/>"

**Comment by DerekYRC** [comment]
@CarsonLuo ClassPathBeanDefinitionScanner#doScan方法中注册了AutowiredAnnotationBeanProcessor，我跑单测没问题啊，你跑的是哪个单测类？报错是？
![image](https://user-images.githubusercontent.com/44155264/233815758-917357d0-1bf1-4d76-80eb-2085206a0eb1.png)

**Comment by CarsonLuo** [comment]
抱歉, 看错了

**Comment by DerekYRC** [comment]
@CarsonLuo 没事没事，有问题随时沟通
